import { cormorant, cormorantLightItalic, manrope } from './fonts'
import './globals.css'
import { LanguageProvider } from '@/context/LanguageContext'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${manrope.variable} ${cormorant.variable} ${cormorantLightItalic.variable}`}
		>
			<body>
				<LanguageProvider>{children}</LanguageProvider>
			</body>
		</html>
	)
}
